spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/dina_db?currentSchema=seqdb
    username: seqdb_webapp
    password: changeme
  liquibase:
    user: seqdb_migration
    password: changeme2
keycloak:
  enabled: true
  realm: dina-realm
  auth-server-url: http://192.168.99.100:8081/auth
  resource: dina
  public-client: true
  principal-attribute: preferred_username
  
  # All endpoints require a logged-in user with the "user" role.
  security-constraints:
    - auth-roles:
      - user
      security-collections:
        - patterns:
          - /*
